name: flutter_devarchitecture
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

# The SDK version is 3.22.3

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # firebase
  cloud_firestore: ^5.5.0 #* Android iOS macOS web Windows
  firebase_core: ^3.8.0 #* Android iOS macOS web Windows
  firebase_messaging: ^15.1.6 #* Android iOS macOS web
  firebase_crashlytics: ^4.2.0 #* Android iOS macOS
  firebase_analytics: ^11.3.6 #* Android iOS macOS web
  firebase_remote_config: ^5.2.0 #* Android iOS macOS web
  firebase_performance: ^0.10.0+11 #* Android iOS web

  material_color_utilities: ^0.8.0

  # data
  collection: ^1.18.0 #: All platforms
  data_table_2: ^2.5.15 #: All platforms
  intl: ^0.19.0 #: All platforms

  # state management
  flutter_bloc: ^8.1.6 #: All platforms

  # localization
  flutter_localizations:
    sdk: flutter #: All platforms

  # design
  geekyants_flutter_gauges: ^1.0.4 #: All platforms
  lottie: ^3.1.2 #* Android iOS Linux macOS Windows
  graphic: ^2.3.0 #: All platforms

  # dependency injection
  flutter_modular: ^6.3.4 #: All platforms
  get_it: ^8.0.0 #: All platforms
  provider: ^6.1.2 #: All platforms

  # google places
  google_places_flutter: ^2.0.8 #: All platforms

  # messages toast
  oktoast: ^3.4.0 #: All platforms

  # database
  shared_preferences: ^2.2.3 #: All platforms
  sqflite: ^2.3.3+1 #* Android iOS macOS
  path: ^1.9.0 #: All platforms

  # security
  jwt_decoder: ^2.0.1 #: All platforms
  flutter_secure_storage: ^9.2.2 #: All platforms

  # utils

  internet_connection_checker_plus: ^2.5.2 #: All platforms
  # internet_connection_checker: ^3.0.0

  platform_local_notifications: ^1.0.2 #: All platforms
  # flutter_local_notifications: ^18.0.1


  url_launcher: ^6.3.0 #: All platforms
  dart_amqp: ^0.3.1 #* Android iOS Linux macOS Windows
  battery_plus: ^6.0.1 #: All platforms
  device_info_plus: ^11.1.1
  permission_handler: ^11.3.1 #* Android iOS web Windows
  logger: ^2.4.0 #: All platforms
  file_picker: ^8.0.6 #: All platforms
  path_provider: ^2.1.3 #* Android iOS Linux macOS Windows
  pdf: ^3.11.0 #: All platforms
  image: ^4.2.0 #: All platforms
  excel: ^4.0.2 #: All platforms
  csv: ^6.0.0 #: All platforms
  google_maps_flutter: ^2.7.0 #* Android iOS web
  share_plus: ^10.0.2 #: All platforms
  local_auth: ^2.2.0 #* Android iOS macOS Windows
  qr_code_scanner: ^1.0.1 #* Android iOS
  universal_html: ^2.2.4 #* Android iOS Linux macOS Windows


# dev_dependencies:
  # flutter_test:
  #   sdk: flutter

# dependency_overrides:
#   meta: ^1.12.0
#   flutter_web_plugins:
#     git:
#       url: https://github.com/flutter/flutter.git
#       path: packages/flutter_web_plugins
#       ref: stable

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/403.json
    - assets/404.json
    - assets/loading.json
    - assets/success.json
    - assets/error.json
    - assets/checking.json
    - assets/sending.json
    - assets/feedback.json
  fonts:
    - family: nunito
      fonts:
        - asset: assets/fonts/nunito.ttf
        - asset: assets/fonts/nunito-italic.ttf
          style: italic
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf