name: flutter_devarchitecture
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # firebase
  cloud_firestore: ^5.1.0

  # data
  collection: ^1.18.0
  data_table_2: ^2.5.15
  intl: ^0.19.0

  # state management
  flutter_bloc: ^8.1.6

  # localization
  flutter_localizations:
    sdk: flutter

  # design
  geekyants_flutter_gauges: ^1.0.4
  lottie: ^3.1.2
  graphic: ^2.3.0

  # dependency injection
  flutter_modular: ^6.3.4
  get_it: ^7.7.0

  # google places
  google_places_flutter: ^2.0.8

  # messages toast
  oktoast: ^3.4.0

  # database
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  path: ^1.9.0

  # security
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.2.2

  # utils
  url_launcher: ^6.1.5
  flutter_local_notifications: ^12.0.0
  dart_amqp: ^0.3.1
  device_info_plus:
    git:
      url: https://github.com/fluttercommunity/plus_plugins.git
      path: packages/device_info_plus/device_info_plus

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  meta: ^1.12.0
  flutter_web_plugins:
    git:
      url: https://github.com/flutter/flutter.git
      path: packages/flutter_web_plugins
  material_color_utilities: ^0.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/animations/lottie/404.json
  fonts:
    - family: nunito
      fonts:
        - asset: assets/fonts/nunito.ttf
        - asset: assets/fonts/nunito-italic.ttf
          style: italic