import 'package:flutter/material.dart';
import 'package:flutter_devarchitecture/core/helpers/translate_provider_extension.dart';

class ScreenElementConstants {
  static late BuildContext _context;

  static late String appName;
  static late String returnHomePage;
  static late String loginTitle;
  static late String loginButton;
  static late String registerButton;
  static late String registerTitle;
  static late String usernameHint;
  static late String passwordHint;
  static late String confirmPasswordHint;
  static late String rememberMeHint;
  static late String forgotPasswordHint;
  static late String forgotPasswordTitle;
  static late String sendButton;
  static late String sendAgainButton;
  static late String resendButton;
  static late String resendAgainButton;
  static late String resetButton;
  static late String resetPasswordTitle;
  static late String resetPasswordHint;
  static late String resetPasswordAgainHint;
  static late String resetPasswordButton;
  static late String newInputButton;
  static late String summaryTitle;
  static late String dateFormat;
  static late String timeFormat;
  static late String dateTimeFormat;
  static late String dateHint;
  static late String okButton;
  static late String cancelButton;
  static late String yesButton;
  static late String noButton;
  static late String deleteButton;
  static late String editButton;
  static late String saveButton;
  static late String backButton;
  static late String addButton;
  static late String filterButton;
  static late String clearButton;
  static late String sortButton;
  static late String id;
  static late String logOutButton;
  static late String profileButton;
  static late String notificationsButton;
  static late String changeThemeButton;
  static late String categories;
  static late String sales;
  static late String name;
  static late String days;
  static late String months;
  static late String years;
  static late String hours;
  static late String minutes;
  static late String seconds;
  static late String today;
  static late String yesterday;
  static late String week;
  static late String month;
  static late String year;
  static late String day;
  static late String hour;
  static late String minute;
  static late String second;
  static late String dataTableTitle;

  static late String pdfDownloadTooltip;
  static late String excelDownloadTooltip;
  static late String csvDownloadTooltip;
  static late String imageDownloadTooltip;
  static late String txtDownloadTooltip;
  static late String jsonDownloadTooltip;
  static late String xmlDownloadTooltip;

  static late String pdfShareTooltip;
  static late String excelShareTooltip;
  static late String csvShareTooltip;
  static late String imageShareTooltip;
  static late String txtShareTooltip;
  static late String jsonShareTooltip;
  static late String xmlShareTooltip;
  static late String shareTitle;

  static late String noData;
  static late String noConnection;
  static late String noDataFound;
  static late String error;

  static late String attention;
  static late String warning;
  static late String success;
  static late String information;

  static late String ok;
  static late String cancel;
  static late String yes;
  static late String no;

  static late String email;
  static late String password;

  static late String thisActionCannotBeUndone;
  static late String noDataAvailable;
  static late String vehicleRegistrationNumber;
  static late String vehicleLicensePlate;
  static late String phoneNumber;
  static late String search;

  static void init(BuildContext context) {
    _context = context;

    appName = _translate("AppName");
    returnHomePage = _translate("ReturnHomePage");
    loginTitle = _translate("LoginTitle");
    loginButton = _translate("LoginButton");
    registerButton = _translate("RegisterButton");
    registerTitle = _translate("RegisterTitle");
    usernameHint = _translate("UsernameHint");
    passwordHint = _translate("PasswordHint");
    confirmPasswordHint = _translate("ConfirmPasswordHint");
    rememberMeHint = _translate("RememberMeHint");
    forgotPasswordHint = _translate("ForgotPasswordHint");
    forgotPasswordTitle = _translate("ForgotPasswordTitle");
    sendButton = _translate("SendButton");
    sendAgainButton = _translate("SendAgainButton");
    resendButton = _translate("ResendButton");
    resendAgainButton = _translate("ResendAgainButton");
    resetButton = _translate("ResetButton");
    resetPasswordTitle = _translate("ResetPasswordTitle");
    resetPasswordHint = _translate("ResetPasswordHint");
    resetPasswordAgainHint = _translate("ResetPasswordAgainHint");
    resetPasswordButton = _translate("ResetPasswordButton");
    newInputButton = _translate("NewInputButton");
    summaryTitle = _translate("SummaryTitle");
    dateFormat = _translate("DateFormat");
    timeFormat = _translate("TimeFormat");
    dateTimeFormat = _translate("DateTimeFormat");
    dateHint = _translate("DateHint");
    okButton = _translate("OkButton");
    cancelButton = _translate("CancelButton");
    yesButton = _translate("YesButton");
    noButton = _translate("NoButton");
    deleteButton = _translate("DeleteButton");
    editButton = _translate("EditButton");
    saveButton = _translate("SaveButton");
    backButton = _translate("BackButton");
    addButton = _translate("AddButton");
    filterButton = _translate("FilterButton");
    clearButton = _translate("ClearButton");
    sortButton = _translate("SortButton");
    id = _translate("Id");

    // backend___________________!
    logOutButton = _translate("LogOutButton");
    profileButton = _translate("ProfileButton");
    notificationsButton = _translate("NotificationsButton");
    changeThemeButton = _translate("ChangeThemeButton");
    categories = _translate("Categories");
    sales = _translate("Sales");
    name = _translate("Name");
    days = _translate("Days");
    months = _translate("Months");
    years = _translate("Years");
    hours = _translate("Hours");
    minutes = _translate("Minutes");
    seconds = _translate("Seconds");
    today = _translate("Today");
    yesterday = _translate("Yesterday");
    week = _translate("Week");
    month = _translate("Month");
    year = _translate("Year");
    day = _translate("Day");
    hour = _translate("Hour");
    minute = _translate("Minute");
    second = _translate("Second");
    dataTableTitle = _translate("DataTableTitle");
    pdfDownloadTooltip = _translate("PdfDownloadTooltip");
    excelDownloadTooltip = _translate("ExcelDownloadTooltip");
    csvDownloadTooltip = _translate("CsvDownloadTooltip");
    imageDownloadTooltip = _translate("ImageDownloadTooltip");
    txtDownloadTooltip = _translate("TxtDownloadTooltip");
    jsonDownloadTooltip = _translate("JsonDownloadTooltip");
    xmlDownloadTooltip = _translate("XmlDownloadTooltip");
    pdfShareTooltip = _translate("PdfShareTooltip");
    excelShareTooltip = _translate("ExcelShareTooltip");
    csvShareTooltip = _translate("CsvShareTooltip");
    imageShareTooltip = _translate("ImageShareTooltip");
    txtShareTooltip = _translate("TxtShareTooltip");
    jsonShareTooltip = _translate("JsonShareTooltip");
    xmlShareTooltip = _translate("XmlShareTooltip");
    shareTitle = _translate("ShareTitle");
    noData = _translate("NoData");
    noConnection = _translate("NoConnection");
    noDataFound = _translate("NoDataFound");
    error = _translate("Error");
    attention = _translate("Attention");
    warning = _translate("Warning");
    success = _translate("Success");
    information = _translate("Information");
    ok = _translate("Ok");
    cancel = _translate("Cancel");
    yes = _translate("Yes");
    no = _translate("No");
    email = _translate("Email");
    password = _translate("Password");
    thisActionCannotBeUndone = _translate("ThisActionCannotBeUndone");
    noDataAvailable = _translate("NoDataAvailable");
    vehicleRegistrationNumber = _translate("VehicleRegistrationNumber");
    vehicleLicensePlate = _translate("VehicleLicensePlate");
    phoneNumber = _translate("PhoneNumber");
    search = _translate("Search");
  }

  static String _translate(String key) {
    return _context.translationProvider.translate(key);
  }
}
